/*
 * Forsaken Borders User Service
 *
 * Allows universal login while correctly conforming to OWASP's cheatsheet recommendations.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lunar@forsaken-borders.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Globalization;
using System.IO;
using ForsakenBorders.Backend.Filters;
using ForsakenBorders.Backend.Security;
using ForsakenBorders.Backend.Utilities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi.Models;
using Npgsql;
using Serilog;
using Serilog.Events;

namespace ForsakenBorders.Backend
{
    /// <summary>
    /// Startup
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// Used to access the configs, environment variables, secrets and command line arguments.
        /// </summary>
        public static IConfiguration Configuration { get; private set; }

        private readonly IWebHostEnvironment _hostingEnv;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="env"></param>
        /// <param name="configuration"></param>
        public Startup(IWebHostEnvironment env, IConfiguration configuration)
        {
            _hostingEnv = env;
            Configuration = configuration;
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {
            if (!Configuration.GetValue<bool>("logging:disabled"))
            {
                LoggerConfiguration loggerConfiguration = new LoggerConfiguration()
                    .Enrich.WithThreadId()
                    .MinimumLevel.Is(Configuration.GetValue<LogEventLevel>("logging:level"))
                    .WriteTo.Console(theme: LoggerTheme.Lunar, outputTemplate: Configuration.GetValue("logging:format", "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}] [{Level:u4}] [{ThreadId}] {SourceContext}: {Message:lj}{NewLine}{Exception}"))
                    .WriteTo.File($"logs/{DateTime.Now.ToUniversalTime().ToString("yyyy'-'MM'-'dd' 'HH'_'mm'_'ss", CultureInfo.InvariantCulture)}.log", rollingInterval: Configuration.GetValue<RollingInterval>("logging:rolling_interval"), outputTemplate: Configuration.GetValue("logging:format", "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}] [{Level:u4}] [{ThreadId}] {SourceContext}: {Message:lj}{NewLine}{Exception}"));

                foreach (IConfigurationSection logOverride in Configuration.GetSection("logging:overrides").GetChildren())
                {
                    loggerConfiguration.MinimumLevel.Override(logOverride.Key, Enum.Parse<LogEventLevel>(logOverride.Value));
                }
                Log.Logger = loggerConfiguration.CreateLogger();
                services.AddLogging(loggingBuilder => loggingBuilder.AddSerilog(Log.Logger, true));
            }

            services.AddDbContext<BackendContext>(options =>
            {
                if (Configuration.GetValue<bool>("dev"))
                {
                    // Not using an in-memory database. See https://github.com/dotnet/efcore/issues/16103 and https://github.com/dotnet/efcore/issues/4922
                    options.UseSqlite("Data Source=./dev.db");
                }
                else
                {
                    NpgsqlConnectionStringBuilder connectionBuilder = new();
                    connectionBuilder.ApplicationName = Configuration.GetValue("database:application_name", "Forsaken Borders Backend");
                    connectionBuilder.Database = Configuration.GetValue<string>("database:database_name");
                    connectionBuilder.Host = Configuration.GetValue<string>("database:host");
                    connectionBuilder.Username = Configuration.GetValue<string>("database:username");
                    connectionBuilder.Port = Configuration.GetValue<int>("database:port");
                    connectionBuilder.Password = Configuration.GetValue<string>("database:password");
                    options.UseNpgsql(connectionBuilder.ToString(), options => options.EnableRetryOnFailure(5));
                    options.UseSnakeCaseNamingConvention(CultureInfo.InvariantCulture);
                }
            }, ServiceLifetime.Transient);

            // Documentation!
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1",
                    Title = "Forsaken Borders User Service",
                    Description = "Forsaken Borders User Service",
                    Contact = new OpenApiContact()
                    {
                        Name = "Lunar Starstrum",
                        Url = new Uri("https://github.com/Forsaken-Borders/Backend"),
                        Email = "lunar@forsaken-borders.net"
                    }
                });
                c.CustomSchemaIds(type => type.FullName);
                c.IncludeXmlComments($"{AppContext.BaseDirectory}{Path.DirectorySeparatorChar}{_hostingEnv.ApplicationName}.xml");
                c.OperationFilter<GeneratePathParamsValidationFilter>();
            });

            services.AddAuthentication(ApiKeyAuthenticationHandler.SchemeName).AddScheme<AuthenticationSchemeOptions, ApiKeyAuthenticationHandler>(ApiKeyAuthenticationHandler.SchemeName, ApiKeyAuthenticationHandler.SchemeName, null);
            services.AddAuthorization(options => options.AddPolicy(ApiKeyAuthenticationHandler.SchemeName, policy => policy.RequireAuthenticatedUser()));
            services.AddRouting();
            services.AddControllers();
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app">An instance of a application builder.</param>
        public void Configure(IApplicationBuilder app)
        {
            BackendContext database = app.ApplicationServices.CreateScope().ServiceProvider.GetService<BackendContext>();
            if (Configuration.GetValue<bool>("dev"))
            {
                // Wipe the database if it exists.
                database.Database.EnsureDeleted();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/api/error");
                app.UseStatusCodePages("text/plain", "Status code page, status code: {0}");
            }
            database.Database.EnsureCreated();

            //TODO: Use Https Redirection
            // app.UseHttpsRedirection();
            app.UseHsts();
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSwagger();
            app.UseSwaggerUI();
        }
    }
}
