/*
 * Forsaken Borders User Service
 *
 * Allows universal login while correctly conforming to OWASP's cheatsheet recommendations.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lunar@forsaken-borders.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using ForsakenBorders.Backend.Attributes;
using ForsakenBorders.Backend.Models;
using ForsakenBorders.Backend.Security;
using ForsakenBorders.Backend.Utilities;
using MailKit.Net.Smtp;
using MailKit.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MimeKit;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;

namespace ForsakenBorders.Backend.Controllers
{
    /// <summary>
    /// The User API.
    /// </summary>
    [ApiController]
    [Route("/api/v1/users")]
    public class UsersApiController : ControllerBase
    {
        private readonly BackendContext _database;
        private readonly IConfiguration _configuration;

        /// <summary>
        /// Creates a new instance of the UsersApiController.
        /// </summary>
        /// <param name="forSakenBordersContext">A pre-existing connection to the database.</param>
        /// <param name="configuration">The configuration to use.</param>
        public UsersApiController(BackendContext forSakenBordersContext, IConfiguration configuration)
        {
            _database = forSakenBordersContext;
            _configuration = configuration;
        }

        /// <summary>
        /// Sends a password reset email to the user.
        /// </summary>
        /// <param name="emailAddress"></param>
        /// <response code="200">If the user credentials were correct. Returns the authorization token for the specified user.</response>
        /// <response code="400">If the payload failed to deserialize and verify the input correctly.</response>
        /// <response code="404">If the user was not found.</response>
        /// <response code="410">If the user is deleted.</response>
        [HttpPost]
        [Route("forgot")]
        [AllowAnonymous]
        [ValidateModelState]
        [SwaggerOperation("ApiV1UsersForgotPost")]
        public virtual IActionResult ApiV1UsersForgotPost([FromQuery] string emailAddress)
        {
            if (emailAddress is null)
            {
                return BadRequest("Email address is null.");
            }
            else if (!emailAddress.ValidateEmail())
            {
                return BadRequest("Email address is invalid.");
            }

            User user = _database.Users.FirstOrDefault(databaseUser => databaseUser.Email == emailAddress);
            if (user == null)
            {
                return NotFound("Unknown email.");
            }
            else if (user.IsDeleted)
            {
                return StatusCode(410, "User is deleted. Please contact support if you wish to restore your account.");
            }
            user.RecoveryToken = Guid.NewGuid();
            user.RecoveryTokenExpiration = DateTime.UtcNow.AddMinutes(30);
            _database.SaveChanges();

            SmtpClient client = new();
            client.Connect(_configuration["email:host"], _configuration.GetValue<int>("email:port"), SecureSocketOptions.StartTlsWhenAvailable);
            client.Authenticate(_configuration["email:noreply_address"], _configuration["email:password"]);

            MimeMessage message = new(emailAddress, "Reset your password", $@"
                <p>
                    Hello,
                </p>
                <p>
                    We recently recieved a request to reset your password. Click the link below to reset your password.
                    <a href=""https://{_configuration["domain_name"]}/users/reset/{user.RecoveryToken}"">
                        Reset your password
                    </a>
                </p>
                <p>
                    If you did not request a password reset, please ignore this email.
                </p>
                <p>
                    Thanks,<br>
                    {_configuration["email:noreply_name"]}
                </p>
            ");
            client.Send(message);

            return Ok();
        }

        /// <summary>
        /// Resets the password through a recovery token.
        /// </summary>
        /// <param name="recoveryToken"></param>
        /// <param name="password"></param>
        /// <response code="200">If the recovery token matches, and the password was sucessfully reset.</response>
        /// <response code="400">If the payload failed to deserialize and verify the input correctly.</response>
        /// <response code="404">If the user was not found.</response>
        /// <response code="410">If the user is deleted.</response>
        [HttpPost]
        [Route("forgot/{recoveryToken}")]
        [AllowAnonymous]
        [ValidateModelState]
        [SwaggerOperation("ApiV1UsersForgotRecoveryTokenPost")]
        public virtual IActionResult ApiV1UsersForgotRecoveryTokenPost([FromRoute, Required] Guid? recoveryToken, [FromQuery] string password)
        {
            if (recoveryToken == Guid.Empty)
            {
                return BadRequest("Recovery token is null.");
            }
            else if (password is null)
            {
                return BadRequest("Password is null.");
            }
            else if (password.Length < 8)
            {
                return BadRequest("Password must be more than 8 characters.");
            }
            else if (password.Length > 72)
            {
                return BadRequest("Password must be less than 72 characters.");
            }

            User user = _database.Users.FirstOrDefault(databaseUser => databaseUser.RecoveryToken == recoveryToken);
            if (user is null)
            {
                return NotFound("Unknown recovery token.");
            }
            else if (user.RecoveryTokenExpiration < DateTime.UtcNow)
            {
                return BadRequest("Recovery token has expired.");
            }
            else if (user.IsDeleted)
            {
                return StatusCode(410, "User is deleted. Please contact support if you wish to restore your account.");
            }

            byte[] salt = new byte[1024];
            RandomNumberGenerator.Create().GetBytes(salt);
            user.PasswordSalt = salt;
            user.PasswordHash = password.Argon2idHash(user.PasswordSalt);
            user.RecoveryToken = Guid.Empty;
            user.RecoveryTokenExpiration = DateTime.MinValue;
            _database.SaveChanges();

            return Ok("Password reset.");
        }

        /// <summary>
        /// Attempts to login as a user.
        /// </summary>
        /// <param name="loginPayload"></param>
        /// <response code="200">If the user credentials were correct. Returns the authorization token for the specified user.</response>
        /// <response code="400">If the payload failed to deserialize and verify the input correctly.</response>
        /// <response code="401">If the requester provided the incorrect login credentials.</response>
        /// <response code="404">If the user was not found.</response>
        /// <response code="410">If the user is deleted.</response>
        [HttpPost]
        [Route("login")]
        [AllowAnonymous]
        [ValidateModelState]
        [SwaggerOperation("ApiV1UsersLoginPost")]
        public virtual async Task<IActionResult> ApiV1UsersLoginPost([FromBody] LoginPayload loginPayload)
        {
            if (loginPayload is null)
            {
                return BadRequest("Login payload is null.");
            }
            else if (!loginPayload.Email.ValidateEmail())
            {
                return BadRequest("email is invalid.");
            }
            else if (loginPayload.TokenExpiration != DateTime.MinValue && loginPayload.TokenExpiration < DateTime.UtcNow)
            {
                return BadRequest("token_expiration is in the past.");
            }

            User user = _database.Users.FirstOrDefault(databaseUser => databaseUser.Email == loginPayload.Email);
            if (user is null)
            {
                return NotFound("Unknown email.");
            }
            else if (!loginPayload.Password.Argon2idHash(user.PasswordSalt).SequenceEqual(user.PasswordHash))
            {
                return Unauthorized("Invalid password.");
            }
            else if (user.IsDeleted)
            {
                return StatusCode(410, "User is deleted.");
            }

            user.Token = Guid.NewGuid();
            user.TokenExpiration = loginPayload.TokenExpiration;
            await _database.SaveChangesAsync();
            return Ok(user.Token);
        }

        /// <summary>
        /// Creates a new user.
        /// </summary>
        /// <param name="userPayload"></param>
        /// <response code="200">Success</response>
        /// <response code="201">If the user was created. The user&#x27;s url can be found in the location header, while the token for the user is returned directly.</response>
        /// <response code="400">If the payload failed to deserialize and verify the input correctly.</response>
        /// <response code="409">If the email address provided is already in use.</response>
        [HttpPost]
        [Route("/api/v1/Users")]
        [AllowAnonymous]
        [ValidateModelState]
        [SwaggerOperation("ApiV1UsersPost")]
        public virtual async Task<IActionResult> ApiV1UsersPost([FromBody] UserPayload userPayload)
        {
            if (userPayload is null)
            {
                return BadRequest("User payload is null.");
            }
            else if (!userPayload.Email.ValidateEmail())
            {
                return BadRequest("\"email\" is invalid.");
            }
            else if (userPayload.FirstName?.Trim().Length > 32)
            {
                return BadRequest("\"first_name\" length should be less than or equal to 32 characters in length.");
            }
            else if (userPayload.LastName?.Trim().Length > 32)
            {
                return BadRequest("\"last_name\" length should be less than or equal to 32 characters in length.");
            }
            else if (userPayload.Username?.Trim().Length is > 32 or < 3)
            {
                return BadRequest("\"username\" length should be between 3 and 32 characters in length.");
            }
            else if (_database.Users.Any(databaseUser => databaseUser.Email == userPayload.Email))
            {
                return Conflict("\"email\" is already in use.");
            }

            User newUser = new(userPayload);
            _database.Users.Add(newUser);
            await _database.SaveChangesAsync();
            return Created($"/api/v1/users/{newUser.Id}", newUser.Token);
        }

        /// <summary>
        /// Deletes an existing user.
        /// </summary>
        /// <param name="requestedUserId"></param>
        /// <response code="200">If the user was sucessfully deleted.</response>
        /// <response code="401">If the requester does not have permission to delete the user.</response>
        /// <response code="404">If the user was not found.</response>
        [HttpDelete]
        [Route("{requestedUserId}")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("ApiV1UsersRequestedUserIdDelete")]
        public virtual async Task<IActionResult> ApiV1UsersRequestedUserIdDelete([FromRoute, Required] Guid? requestedUserId)
        {
            User user = await _database.Users.FirstOrDefaultAsync(databaseUser => databaseUser.Token == Guid.Parse(Request.Headers["Authorization"]));
            User requestedUser = await _database.Users.FirstOrDefaultAsync(databaseUser => databaseUser.Id == requestedUserId);
            if (requestedUser is null)
            {
                return NotFound();
            }
            else if (user.Id != requestedUser.Id && !user.Roles.Any(role => role.UserPermissions.HasFlag(Permissions.Delete)))
            {
                return Unauthorized("Missing permissions.");
            }
            else
            {
                requestedUser.IsDeleted = true;
                requestedUser.PasswordHash = null;
                requestedUser.Token = Guid.Empty;
                requestedUser.TokenExpiration = DateTime.UtcNow;
                requestedUser.UpdatedAt = DateTime.UtcNow;
                await _database.SaveChangesAsync();
                return Ok();
            }
        }

        /// <summary>
        /// Gets a specified user. If no user is specified, then it&#x27;ll return the current user.
        /// </summary>
        /// <param name="requestedUserId"></param>
        /// <response code="200">If the user was found.</response>
        /// <response code="404">If the user was not found.</response>
        /// <response code="410">If the user was deleted.</response>
        [HttpGet]
        [Route("{requestedUserId}")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("ApiV1UsersRequestedUserIdGet")]
        public virtual async Task<IActionResult> ApiV1UsersRequestedUserIdGet([FromRoute, Required] Guid? requestedUserId)
        {
            User requestedUser = await _database.Users.FirstOrDefaultAsync(databaseUser => databaseUser.Id == requestedUserId);
            return requestedUser is null
                ? NotFound()
                : requestedUser.IsDeleted
                    ? StatusCode(410, requestedUser) : Ok(requestedUser);
        }

        /// <summary>
        /// Edits an existing user.
        /// </summary>
        /// <param name="requestedUserId"></param>
        /// <param name="userPayload"></param>
        /// <response code="200">If the user was edited.</response>
        /// <response code="304">If the user was not changed.</response>
        /// <response code="400">If the payload failed to deserialize and verify the input correctly.</response>
        /// <response code="401">If the requester does not have permission to edit the user.</response>
        /// <response code="404">If the user was not found.</response>
        /// <response code="409">If the email address provided is already in use.</response>
        [HttpPut]
        [Route("{requestedUserId}")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("ApiV1UsersRequestedUserIdPut")]
        public virtual async Task<IActionResult> ApiV1UsersRequestedUserIdPut([FromRoute, Required] Guid? requestedUserId, [FromBody] UserPayload userPayload)
        {
            if (userPayload is null)
            {
                return BadRequest("User Payload is null.");
            }
            else if (requestedUserId == Guid.Empty)
            {
                return BadRequest("\"id\" should not be null.");
            }

            User user = await _database.Users.FirstOrDefaultAsync(databaseUser => databaseUser.Token == Guid.Parse(Request.Headers["Authorization"]));
            User requestedUser = await _database.Users.FirstOrDefaultAsync(databaseUser => databaseUser.Id == requestedUserId);
            if (requestedUser is null)
            {
                return NotFound();
            }
            else if (!userPayload.Email.ValidateEmail())
            {
                return BadRequest("email is invalid.");
            }
            else if (userPayload.FirstName.Trim().Length > 32)
            {
                return BadRequest("first_name length should be less than or equal to 32 characters in length.");
            }
            else if (userPayload.LastName.Trim().Length > 32)
            {
                return BadRequest("last_name length should be less than or equal to 32 characters in length.");
            }
            else if (userPayload.Username.Trim().Length > 32)
            {
                return BadRequest("username length should be less than or equal to 32 characters in length.");
            }
            else if (userPayload.Username.Trim().Length < 3)
            {
                return BadRequest("username length should be greater than or equal to 3 characters in length.");
            }
            else if (_database.Users.Any(databaseUser => databaseUser.Email == userPayload.Email && databaseUser.Id != requestedUser.Id))
            {
                return Conflict("email is already in use.");
            }
            else if (user.Id != requestedUserId && !user.Roles.Any(role => role.UserPermissions.HasFlag(Permissions.EditAll)))
            {
                return Unauthorized("Missing permissions.");
            }
            else if (userPayload.Equals(requestedUser))
            {
                return StatusCode(304);
            }

            requestedUser.Email = userPayload.Email;
            byte[] salt = new byte[1024];
            RandomNumberGenerator.Create().GetBytes(salt);
            requestedUser.PasswordSalt = salt;
            requestedUser.PasswordHash = userPayload.Password.Argon2idHash(requestedUser.PasswordSalt);
            requestedUser.Username = userPayload.Username;
            requestedUser.FirstName = userPayload.FirstName;
            requestedUser.LastName = userPayload.LastName;
            await _database.SaveChangesAsync();
            return Ok();
        }
    }
}
